version: 2

project_name: agentx

before:
  hooks:
    - go mod tidy -C ./packages/cli
    - pnpm -r --filter '*-cli' --filter '!./packages/cli' run build

builds:
  - main: ./packages/cli
    binary: agentx
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "agentx_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: packages/claudecode-cli/**/*
        dst: lib/packages/claudecode-cli
        strip_parent: true
      - src: packages/copilot-cli/**/*
        dst: lib/packages/copilot-cli
        strip_parent: true
      - src: packages/augment-cli/**/*
        dst: lib/packages/augment-cli
        strip_parent: true
      - src: packages/opencode-cli/**/*
        dst: lib/packages/opencode-cli
        strip_parent: true

brews:
  - repository:
      owner: jefelabs
      name: homebrew-agentx
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/jefelabs/agentx
    description: Developer infrastructure for AI agent configurations
    license: MIT
    install: |
      bin.install "agentx"
      (lib/"packages").install Dir["lib/packages/*"]
    test: |
      assert_match version.to_s, shell_output("#{bin}/agentx version")

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
